name: 'Release Python package'
description: 'Build wheels and sdist and upload to PyPI'
inputs:
  test_extras:
    description: Any extras_requires modifier that should be used to install the package for testing
    required: false
    default: ''
  test_command:
    description: The command to run to test the package (will be run in a temporary directory)
    required: false
    default: ''
runs:
  using: "composite"
  steps:

  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Install python-build and twine
    run: python -m pip install pip build twine --upgrade

  - name: Build source distribution
    run: python -m build --sdist .

  - name: List result
    run: ls -l dist

  - name: Installing source distribution
    run: python -m pip install --force-reinstall $(find dist -name "*.tar.gz")[{{ inputs.test_extras }}]
    if: ${{ inputs.test_extras != '' }}

  - name: Installing source distribution
    run: python -m pip install --force-reinstall $(find dist -name "*.tar.gz")
    if: ${{ inputs.test_extras == '' }}

 - name: Test source distribution
    run: {{ inputs.test_command }}
    if: ${{ inputs.test_command != '' }}
    working-directory: ${{ runner.temp }}
