on: [push]

jobs:
  build_wheels:
    name: Do release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: astrofrog/action-sandbox@v1
