on: [push]

jobs:
  build_wheels:
    name: Do release
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: astrofrog/action-sandbox@main
        with:
          test_command: pytest --pyargs test_package
